services:
  frontend:
    image: react-app
    volumes:
      - .:/app
    ports:
      - "3001:80"

  php:
    build:
      context: ./php
    volumes:
      - ./backend:/var/www/html

  nginx:
    image: nginx:latest
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
