services:
  frontend:
    image: react-app
    volumes:
      - .:/app

  php:
    build:
      context: ./php
    volumes:
      - ./backend:/var/www/html
      - ./db:/db

  nginx:
    image: nginx:latest
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - frontend


